---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: traefik-egress-prometheus
  namespace: traefik
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: traefik-traefik
      app.kubernetes.io/name: traefik
  egress:
    - toServices:
        - k8sService:
            serviceName: kube-prometheus-stack-prometheus
            namespace: monitoring
      toPorts:
        - ports:
            - port: "9090"
              protocol: TCP
