---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: traefik-egress-cilium
  namespace: traefik
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: traefik-traefik
      app.kubernetes.io/name: traefik
  egress:
    - toServices:
        - k8sServiceSelector:
            selector:
              matchLabels:
                k8s-app: hubble-ui
            namespace: kube-system
        - k8sServiceSelector:
            selector:
              matchLabels:
                k8s-app: hubble-relay
            namespace: kube-system
      toPorts:
        - ports:
            - port: "8081"
              protocol: TCP
