---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudnative-pg-egress-wiki-postgres.yaml
  - cnpg-postgres.yaml
  - minio-ingress-wiki-postgres.yaml
  - prometheus-egress-wiki-postgres.yaml
