---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  component: paperless
resources:
  - networkpolicies
  - deployment.yaml
  - ingress.yaml
  - persistentvolumeclaim.yaml
  - secret.yaml
  - service.yaml
