apiVersion: v1
kind: Secret
metadata:
    name: kube-prometheus-stack-grafana-settings
    namespace: observability
type: Opaque
stringData:
    GRAFANA_AUTH_CLIENT_ID: ENC[AES256_GCM,data:v6a89LeuLahzIct7AM9GeAhJ,iv:6Jlvn5lqC84/0v+mqGgZG0OhhOsLvoSkTHFzCJHTbFo=,tag:kunNyJwokjUwvGTxDj5+9Q==,type:str]
    GRAFANA_AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:S2Z/tkS+DLpEEohiCebPFC9hhVyvyLRpabOfl4s3qE4=,iv:wMRZJrBBdEj3hdbRPgW4H0oFIIa0tocEdhYwROhese8=,tag:bYFVJ5UKln10SJ6IJv8aYw==,type:str]
sops:
    lastmodified: "2026-01-10T13:16:50Z"
    mac: ENC[AES256_GCM,data:8GKyBbYS2syz64WSS0OjYkoQ9Fro6qTbc+lfUWKAQVtuo1B2rvVdmaKy/kg5oYR1IwiWZJ7usAO7RsClJARYqk4kCMy6nKOKTJ+tWYXMFyNro2eAPXmC4pLnZoZdO1G9vvyCftqFRXoXh7JeYKrfD2erkCvJf/z3ETpMVJihaiY=,iv:JRgqyKnpM0lqWhNp6s45gvLGEAO1ynuXPT1s4qJ/YBk=,tag:1uj7aMazuGjiMoF3gGnV3Q==,type:str]
    pgp:
        - created_at: "2026-01-10T13:16:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ/9HHZ1bwFusZVEk0Ef4NWekS31foePdAYAnUzkLAKkPjcO
            gY5gOKw87wMrGz6szchji1TW8oNYiwhRzYqe210a2Fx5K2svhigs6wLn5z7nACYC
            kIlS3OdDQ5yX4YAs8RAz75sQZdRcSBRhZ+pkSCX9v7Jv/3LbAAD5++DaDp9cYMSM
            /0JIJA4cJDTByKKY9mIjD5Wwek4R692LKu3EDYchsQgTzVgJ72Aeemn1HxHaO1sl
            eIxVLLxMY76N+FI9XPMiB6cBfrg5pdtRQTIi3Lc4Uokol4QRL0JDG51qmPANyzoq
            wMC9Q7bjxvBddFXy/EThDv0RlJ5rABWi9DbpPgl06tVynjLJdYTDTHr2g39NJLJ6
            4Zx4LmxxDUxcj31nCr0H7p5NhqI2fgbJ17pIZynAkYZjDkAoPgLcDO/5RJqABcGb
            EeHI2NJ6MGiPIeXcFy/3IvtERAYDo5ptssK2cZQi2HdXHd65mvyxTocw08eSD/d5
            IdP/GThdXZ7VcOf7S46XAqmUnN0L5+lPB5xpNlYp8RNaRvQyXKCUZpVurSLQfuKy
            p9kbCwzz3p0pWHzsSYN9TrS/9wvbN0zvUOONnQX0WB5qaQGAb64f8UqlE0bx6cWB
            0rJupkQKIXKVloJmMuC4iRKP5oqKMGeC7qKnBLLJ+ndUV1cKJecaA/MxU65JMqvU
            aAEJAhBNcqrIYrW8p30j3as2cP7ueWYkNMP1AWAMqYq7/Jev9ihU36XzhasViBI1
            MBt2HCSc593YH9do7EV+FA1X9Pop99aBo2E4f+iaWOyMyidh0fKiLO267N8aq+WH
            LW6HiePyxt7Y
            =3FC6
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: kube-prometheus-stack-helm-values
    namespace: observability
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:ReLkE42wBC9CRZqvpu3eIGT5ss89ZxfXBMnx4xx0oH9PIxHG1P5jiOwFBrmDdlOrjy+5CyoHU0NvvQ/PFtOr6nHlYMbiGy/vL1RVTocoGiog60ejebEriyFuiPbKm75GIDduoNPfRy2cwVhhhAhWCgjqvWCdRE7EYhQ5rKnrYMj5QBjZ+Nxy5t+Qv4pBHKJ59dVUSWNpXp2PXPfCfgoHeiQMGo+EYGFzyj4NXa0yZlEPQiJyI10GAjWKiCYrdywn6TKsVw==,iv:hxH6NdFRByP6RT3aKG/vof+77QNs0j1RzXdQOWH2DGU=,tag:/65TkrucuKTuZA6/TJKbWQ==,type:str]
sops:
    lastmodified: "2026-01-10T13:16:50Z"
    mac: ENC[AES256_GCM,data:8GKyBbYS2syz64WSS0OjYkoQ9Fro6qTbc+lfUWKAQVtuo1B2rvVdmaKy/kg5oYR1IwiWZJ7usAO7RsClJARYqk4kCMy6nKOKTJ+tWYXMFyNro2eAPXmC4pLnZoZdO1G9vvyCftqFRXoXh7JeYKrfD2erkCvJf/z3ETpMVJihaiY=,iv:JRgqyKnpM0lqWhNp6s45gvLGEAO1ynuXPT1s4qJ/YBk=,tag:1uj7aMazuGjiMoF3gGnV3Q==,type:str]
    pgp:
        - created_at: "2026-01-10T13:16:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ/9HHZ1bwFusZVEk0Ef4NWekS31foePdAYAnUzkLAKkPjcO
            gY5gOKw87wMrGz6szchji1TW8oNYiwhRzYqe210a2Fx5K2svhigs6wLn5z7nACYC
            kIlS3OdDQ5yX4YAs8RAz75sQZdRcSBRhZ+pkSCX9v7Jv/3LbAAD5++DaDp9cYMSM
            /0JIJA4cJDTByKKY9mIjD5Wwek4R692LKu3EDYchsQgTzVgJ72Aeemn1HxHaO1sl
            eIxVLLxMY76N+FI9XPMiB6cBfrg5pdtRQTIi3Lc4Uokol4QRL0JDG51qmPANyzoq
            wMC9Q7bjxvBddFXy/EThDv0RlJ5rABWi9DbpPgl06tVynjLJdYTDTHr2g39NJLJ6
            4Zx4LmxxDUxcj31nCr0H7p5NhqI2fgbJ17pIZynAkYZjDkAoPgLcDO/5RJqABcGb
            EeHI2NJ6MGiPIeXcFy/3IvtERAYDo5ptssK2cZQi2HdXHd65mvyxTocw08eSD/d5
            IdP/GThdXZ7VcOf7S46XAqmUnN0L5+lPB5xpNlYp8RNaRvQyXKCUZpVurSLQfuKy
            p9kbCwzz3p0pWHzsSYN9TrS/9wvbN0zvUOONnQX0WB5qaQGAb64f8UqlE0bx6cWB
            0rJupkQKIXKVloJmMuC4iRKP5oqKMGeC7qKnBLLJ+ndUV1cKJecaA/MxU65JMqvU
            aAEJAhBNcqrIYrW8p30j3as2cP7ueWYkNMP1AWAMqYq7/Jev9ihU36XzhasViBI1
            MBt2HCSc593YH9do7EV+FA1X9Pop99aBo2E4f+iaWOyMyidh0fKiLO267N8aq+WH
            LW6HiePyxt7Y
            =3FC6
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    version: 3.11.0
