---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-blackbox-exporter
  namespace: observability
spec:
  interval: 20m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      version: 11.8.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 30m
  values:
    fullnameOverride: blackbox-exporter
    pspEnabled: false
    config:
      modules:
        http_2xx_higher_timeout:
          prober: http
          timeout: 30s
          http:
            valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
            follow_redirects: true
            preferred_ip_protocol: ip4
        newsnab:
          prober: http
          timeout: 5s
          http:
            valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
            follow_redirects: true
            preferred_ip_protocol: ip4
            fail_if_body_not_matches_regexp: ["${NEWSNAB_REGEX}"]
    ingress:
      enabled: false
    serviceMonitor:
      enabled: true
      defaults:
        interval: 15m
        scrapeTimeout: 30s
        follow_redirects: false
      targets:
        - name: ${BASE_DOMAIN/./-}
          url: https://sso.${BASE_DOMAIN}
        - name: pihole-keepalive
          url: https://pihole.local.${BASE_DOMAIN}/admin/login
        - name: pihole-1
          url: https://pihole.tools.${BASE_DOMAIN}/admin/login
        - name: pihole-2
          url: https://pihole.vpn.${BASE_DOMAIN}/admin/login
        - name: traefik-tools
          url: https://traefik.tools.${BASE_DOMAIN}
        - name: traefik-vpn
          url: https://traefik.vpn.${BASE_DOMAIN}
        - name: diskstation
          url: https://ds.local.${BASE_DOMAIN}
          scrapeTimeout: 2m
          module: http_2xx_higher_timeout
    prometheusRule:
      enabled: true
      rules:
        - alert: Newsnab
          expr: last_over_time(probe_failed_due_to_regex{target="newsnab"}[60m]) == 1
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: Newsnab API is expired
            description: Newsnab API for «{{ $labels.target }}» is expired
        - alert: SSLCertExpiringSoon
          annotations:
            description: SSL certificate will expire in {{ $value | humanizeDuration }} (instance {{ $labels.instance }})
            summary: SSL certificate «{{ $labels.instance }}» expires soon
          expr: |
            (
              last_over_time(probe_ssl_earliest_cert_expiry[1h]) - time()
            )
            and
            (
              last_over_time(probe_ssl_earliest_cert_expiry[1h]) > 0
              and
              (last_over_time(probe_ssl_earliest_cert_expiry[1h]) - time()) < 29 * 86400
            )
          for: 5m
          labels:
            severity: warning
        - alert: BlackboxProbeFailed
          annotations:
            description: The host «{{ $labels.instance }}» is currently unreachable
            summary: Host is unreachable
          expr: |
            min_over_time(probe_success[40m]) == 0
          for: 5m
          labels:
            severity: critical
        - alert: BlackboxProbeNoData
          annotations:
            description: No probe data received for «{{ $labels.instance }}»
            summary: Blackbox probe has no data
          expr: absent_over_time(probe_success[40m])
          for: 10m
          labels:
            severity: critical
