---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - egress-gitlab-migrations.yaml
  - egress-gitlab-shared-secrets.yaml
  - egress-gitlab-upgrade-check.yaml
  - envoy-gateway-egress-gitlab.yaml
  - envoy-gateway-internal-egress-gitlab.yaml
  - gitlab-gitaly.yaml
  - gitlab-registry.yaml
  - gitlab-shell.yaml
  - gitlab-sidekiq.yaml
  - gitlab-toolbox.yaml
  - gitlab-webservice.yaml
