---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - cloudflare-operator.yaml
  - debug.yaml
  - filebrowser.yaml
  - gitlab.yaml
  - healthchecks.yaml
  - k8up.yaml
  - keyclaok.yaml
  - kubernetes-dashboard.yaml
  - media.yaml
  - metallb-system.yaml
  - minio.yaml
  - monitoring.yaml
  - nextcloud.yaml
  - paperless.yaml
  - reloader.yaml
  - renovate.yaml
  - storage-system.yaml
  - syncflaer.yaml
  - traefik.yaml
  - wallabag.yaml
  - wiki.yaml
