---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - envoy-gateway-egress-blackbox-exporter.yaml
  - prometheus-blackbox-exporter.yaml
  - prometheus-egress-prometheus-blackbox-exporter.yaml
