---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: prometheus-egress-prometheus-blackbox-exporter
  namespace: observability
spec:
  description: "Policy for prometheus-egress-prometheus-blackbox-exporter"
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: kube-prometheus-stack-prometheus
      app.kubernetes.io/name: prometheus
  egress:
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: prometheus-blackbox-exporter
            app.kubernetes.io/name: prometheus-blackbox-exporter
            "k8s:io.kubernetes.pod.namespace": observability
      toPorts:
        - ports:
            - port: "9115"
              protocol: TCP
