apiVersion: v1
kind: Secret
metadata:
    name: kube-prometheus-stack-grafana-settings
    namespace: observability
type: Opaque
stringData:
    GRAFANA_AUTH_CLIENT_ID: ENC[AES256_GCM,data:NKLhKOiSade5JWeK7B0uuf+3,iv:mh1fhBrlC1DbuhSWIWrz7pwt0wu20IRXf+L5bepVTmw=,tag:t3Dbr9LcIMxXA5TDlZdeiA==,type:str]
    GRAFANA_AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:ZVAzni7NvGZNFb9xmB363vg2l1p4lZWK40IUKzehQ/I=,iv:EpyWEFgeWtlHpTMt2P6toadUBRc/mFTqbxw+lySHV/k=,tag:TqmZuShg6ei/hxRfg1woag==,type:str]
sops:
    lastmodified: "2026-01-01T12:50:17Z"
    mac: ENC[AES256_GCM,data:ui/7SWdcHbAurocu6Z5eV1k/JbV8Hb77F3YmoodZ9u5A6dq8E0KXHSQ7KmEQvw2UI9Sw/spUI7SDWFa1UxEhUFJBeoTB+O/j4hiigB+xhDIb9UeF5OZV9q7faUY/uekVzgRbRaKcOO6uAQuMm1F61kH8Qj6RFAnC9qDuoUvBVB0=,iv:O9NoDlR9RS6Lm3xHCpd9zHx5isxH64opVkrNfPtEvWI=,tag:92t1SgObIiniiiRlqoH8LQ==,type:str]
    pgp:
        - created_at: "2026-01-01T12:50:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ/9FgJt4d0M4S9BX/41TnWNfKeUqQhTFylX7Mfvd/XivQmM
            rU5fm6OF3APk07tXtCLWyyk7CUUcyt8X5l4+SKLwgu88ADz2Hp/Q5ZByM5JoY5wV
            pYRQfIWsrpvP1TXUfdrSkoT9gdDsKQcPy3UrHuqRFsYpeWjxDT/Jguhr6ZJ/DABU
            Kadnoos1dSNCYAQxQAqLascx4nWrNtNshE2j1SjHd6G3hm9tpvhTQKRnH5/qsp8r
            RI0dZ8jvCV4zm0iFczD0tgDQbaFuYzUrzuP04nHU42jdZXhJvAmD90mPZ1Ty/leQ
            rn9LNkWJsohndfkPWATiOvTOthptRB64ZDyVdy1G32mrIvoXVcXJrZnpuICJTuM9
            kvCvy8t3U6opanMEMmBhIUgBwz7yn/N/GNy0vFfhauyNnzS/cRhiFoiPUYJKQ8d/
            JfekY5G/2EVTgu//HjQ68N+/t+6BNL0CZKjfdLUrYCt4dKjGPhWVIKWWU3eLL+rT
            iyqF8nhw/mpZkaZ+ZQtBA4eRa1gcIkM3zyMSFTZMUhkWNVOAhmdfmUpCi9F+qh53
            FciTgD/uMRYQSn4/1zmceNNbZqnOjJOlpmfXYO7iLEXn8xCej83IosoH40NQwfWT
            6G+zYyM+aY5CH6LGcqyb1FQYIh0GH7MiZVqxekjf7btjgD/ycittr53/CwYa8FjU
            aAEJAhDjbnORVnAbJRb/3jGjSMK2hXWcShH5aCpvLDhIZUDc9GvzVKx9qGCCnePq
            vsNt1t5+jIWlctFP0z5lIZUpsWjgHDu5fUGNKdw4+u9yjkvJD2u8i4WE2mKZHQmZ
            jLjaUHyoNWsP
            =VjrF
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: kube-prometheus-stack-helm-values
    namespace: monitoring
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:F/uPH3AtdGpqarG39fUGm2aLBBR3sX0iKM4KBM/p922vzno31jIOk0ZmtBeJgSjm67sZhMXgqjEQpF6HbGMTjDTKRtNeNkAiug7hTzpaVMAXoROPXXfNDxPCKm69hHKpWsPblrMTn/qal2MDDCFyHAAxXzyXYLsRJHeoK9cpitBWcScHk2m+NVzlHsnYHcvkIKj+jqjuQf+PRhJ/4OAc6TOudiiPgS1+WloWpqWZ+KY6Fvi28BG6/m2O/8amop7YaYp68g==,iv:vstwktilPpAgvsMcB2osm4aF1aqHeTVdwr4i1HmLh6s=,tag:4s286eS79dWM+c9Mx1zMCQ==,type:str]
sops:
    lastmodified: "2026-01-01T12:50:17Z"
    mac: ENC[AES256_GCM,data:ui/7SWdcHbAurocu6Z5eV1k/JbV8Hb77F3YmoodZ9u5A6dq8E0KXHSQ7KmEQvw2UI9Sw/spUI7SDWFa1UxEhUFJBeoTB+O/j4hiigB+xhDIb9UeF5OZV9q7faUY/uekVzgRbRaKcOO6uAQuMm1F61kH8Qj6RFAnC9qDuoUvBVB0=,iv:O9NoDlR9RS6Lm3xHCpd9zHx5isxH64opVkrNfPtEvWI=,tag:92t1SgObIiniiiRlqoH8LQ==,type:str]
    pgp:
        - created_at: "2026-01-01T12:50:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ/9FgJt4d0M4S9BX/41TnWNfKeUqQhTFylX7Mfvd/XivQmM
            rU5fm6OF3APk07tXtCLWyyk7CUUcyt8X5l4+SKLwgu88ADz2Hp/Q5ZByM5JoY5wV
            pYRQfIWsrpvP1TXUfdrSkoT9gdDsKQcPy3UrHuqRFsYpeWjxDT/Jguhr6ZJ/DABU
            Kadnoos1dSNCYAQxQAqLascx4nWrNtNshE2j1SjHd6G3hm9tpvhTQKRnH5/qsp8r
            RI0dZ8jvCV4zm0iFczD0tgDQbaFuYzUrzuP04nHU42jdZXhJvAmD90mPZ1Ty/leQ
            rn9LNkWJsohndfkPWATiOvTOthptRB64ZDyVdy1G32mrIvoXVcXJrZnpuICJTuM9
            kvCvy8t3U6opanMEMmBhIUgBwz7yn/N/GNy0vFfhauyNnzS/cRhiFoiPUYJKQ8d/
            JfekY5G/2EVTgu//HjQ68N+/t+6BNL0CZKjfdLUrYCt4dKjGPhWVIKWWU3eLL+rT
            iyqF8nhw/mpZkaZ+ZQtBA4eRa1gcIkM3zyMSFTZMUhkWNVOAhmdfmUpCi9F+qh53
            FciTgD/uMRYQSn4/1zmceNNbZqnOjJOlpmfXYO7iLEXn8xCej83IosoH40NQwfWT
            6G+zYyM+aY5CH6LGcqyb1FQYIh0GH7MiZVqxekjf7btjgD/ycittr53/CwYa8FjU
            aAEJAhDjbnORVnAbJRb/3jGjSMK2hXWcShH5aCpvLDhIZUDc9GvzVKx9qGCCnePq
            vsNt1t5+jIWlctFP0z5lIZUpsWjgHDu5fUGNKdw4+u9yjkvJD2u8i4WE2mKZHQmZ
            jLjaUHyoNWsP
            =VjrF
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    version: 3.11.0
