apiVersion: v1
kind: Secret
metadata:
    name: kube-prometheus-stack-grafana-settings
    namespace: observability
type: Opaque
stringData:
    GRAFANA_AUTH_CLIENT_ID: ENC[AES256_GCM,data:P9RWuhxitoNq0Po/nkEqSLGH,iv:NcCcXotjnwJozWFjrbPGfFZ00H9XPvtV+HP872lG2UM=,tag:sL1Znh1wTN13lTRbRRBkdw==,type:str]
    GRAFANA_AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:waW5co09cPpvjv5WZni+7iHJ/2eW8TjhlE3Ch1owGwQ=,iv:OnA7ygwfRwcPTjv8lozscPx4RhrdpMmmnVEzwGXt5yU=,tag:KS2Qc8SG9MI3k+t5m4+b+Q==,type:str]
sops:
    lastmodified: "2026-01-01T13:03:27Z"
    mac: ENC[AES256_GCM,data:6H8kPO34X6Pbjxf2I8YDMzFeMMllg5wBcFHJLS3mBQN5BvkOkNcBDI1mHr1zHJzpYOXJtHp7JnGbGyHRl41ko5OrmzWkX8qtlmNBO8rl1Sj9hVZk9piq2AS3oAU7V1rpdlz/yYAY/uthTq5U36uYd240E8xTwbI4/ShewgODuZw=,iv:WR2nErNasBUvvWBgkkPQkrqCtOiwGkihi4ROerj0j+I=,tag:dQv3nszZ82Bukgtj8mt3aA==,type:str]
    pgp:
        - created_at: "2026-01-01T13:03:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ/8DUjfsv9Fz0wDtVnRTN2PUrJAFfb+cd7ErGkGq13DXJ6H
            iFcK+dlpg0t5AawV2zRcjbe2ejtVqAWnOkrwja3imZ1fs/aoGAS0JJqWGJ8au8gm
            aCxpHg+cBDa4aX8TQfpGrKrx62byBTlbCyzgnGviwQqbgSCEqxX1WXVNtER3GvEf
            Ljuc3seedMB4J2ll68tXE+SR++ThurrrPHJ9h2rxrySWSYhW5BqDfXZlteVHQ9PV
            Yu5GJUVsVYZTrPgIjj7iTp8aT7dgU2ZbcTDRmCs9bus5y3PEW2ly6zD9ZoxpBZtm
            fpDwK6OmEnxJ+C6ujfU3cRLMQBThEawsqHtbdb1x0UImF68trBX8my7hGLF7v6NV
            x81mfHBBYzkVLn58VVmByiKXpkoelTSKP4x57RiBHQg/u6dNAc4MhxFjJRVgVtGO
            da5Ofbr63IWldD1HiwS4dXVL8gjP9YPcH34k+yJRoGZpRYfnPTVJsp5VRqhLwlRt
            LcXLABtW/tg83DmW5WtxdCM+pIZ6p5z/Zei3IScsNMyZVOINEAi9Thia5E+Ns6/k
            XJBKWlkzGMlKwM/K0Y31eaO+lGl0RQA2cgyQF3GR++F2U0mydSrscXNJrwesJtdj
            okMZ1h+B0xE1d/pQ9zj+FAJEOrV1GbU5Z/47Ad6CsFE5Ouhf/fS+vj/pvTTR2pjU
            aAEJAhDGzDg9BlKNAzJmDimLBA/s/fI91pbmE9NFJNcPfOP5bMXRbxQmvlBjWZfw
            pBDU96YSC0CGMbFuDv/A6AbUZMolQDJf37FBqGfLSRzd1srjYheYoX3sGnSnTuJQ
            h5GxafqJb+6w
            =y1Cu
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: kube-prometheus-stack-helm-values
    namespace: observability
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:NWjsztnGc+sm871ocHM3yw+DHwusRxD0BKl+bjwFRlXLbDp/J1MBJZFl9+l0M3z5+1tkACRXojsStAi1ZSYGQ4FDinCAZVCmEIq81B3xbI2LbQxReQuYyEw1KUOFDf/khalLBhprl2J+AL0Qr1pEazQACBoA+cCFoitDbRcWIKL+hEw63yqLV9l6aXkktPu6RScmL7hihYFqb7n9Zy+EJgEdQ1ohPNz6DrcC2PuyqNK8Nw6DnSYFqViDAmPLFZrXsoic2A==,iv:huSgn7RRc6hOp+7Dv2VjCuqiiHCiZ0hKHvREx9LNqmw=,tag:P75pJuKhxdXqTKIcLE/U1Q==,type:str]
sops:
    lastmodified: "2026-01-01T13:03:27Z"
    mac: ENC[AES256_GCM,data:6H8kPO34X6Pbjxf2I8YDMzFeMMllg5wBcFHJLS3mBQN5BvkOkNcBDI1mHr1zHJzpYOXJtHp7JnGbGyHRl41ko5OrmzWkX8qtlmNBO8rl1Sj9hVZk9piq2AS3oAU7V1rpdlz/yYAY/uthTq5U36uYd240E8xTwbI4/ShewgODuZw=,iv:WR2nErNasBUvvWBgkkPQkrqCtOiwGkihi4ROerj0j+I=,tag:dQv3nszZ82Bukgtj8mt3aA==,type:str]
    pgp:
        - created_at: "2026-01-01T13:03:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ/8DUjfsv9Fz0wDtVnRTN2PUrJAFfb+cd7ErGkGq13DXJ6H
            iFcK+dlpg0t5AawV2zRcjbe2ejtVqAWnOkrwja3imZ1fs/aoGAS0JJqWGJ8au8gm
            aCxpHg+cBDa4aX8TQfpGrKrx62byBTlbCyzgnGviwQqbgSCEqxX1WXVNtER3GvEf
            Ljuc3seedMB4J2ll68tXE+SR++ThurrrPHJ9h2rxrySWSYhW5BqDfXZlteVHQ9PV
            Yu5GJUVsVYZTrPgIjj7iTp8aT7dgU2ZbcTDRmCs9bus5y3PEW2ly6zD9ZoxpBZtm
            fpDwK6OmEnxJ+C6ujfU3cRLMQBThEawsqHtbdb1x0UImF68trBX8my7hGLF7v6NV
            x81mfHBBYzkVLn58VVmByiKXpkoelTSKP4x57RiBHQg/u6dNAc4MhxFjJRVgVtGO
            da5Ofbr63IWldD1HiwS4dXVL8gjP9YPcH34k+yJRoGZpRYfnPTVJsp5VRqhLwlRt
            LcXLABtW/tg83DmW5WtxdCM+pIZ6p5z/Zei3IScsNMyZVOINEAi9Thia5E+Ns6/k
            XJBKWlkzGMlKwM/K0Y31eaO+lGl0RQA2cgyQF3GR++F2U0mydSrscXNJrwesJtdj
            okMZ1h+B0xE1d/pQ9zj+FAJEOrV1GbU5Z/47Ad6CsFE5Ouhf/fS+vj/pvTTR2pjU
            aAEJAhDGzDg9BlKNAzJmDimLBA/s/fI91pbmE9NFJNcPfOP5bMXRbxQmvlBjWZfw
            pBDU96YSC0CGMbFuDv/A6AbUZMolQDJf37FBqGfLSRzd1srjYheYoX3sGnSnTuJQ
            h5GxafqJb+6w
            =y1Cu
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    version: 3.11.0
