---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: prometheus-egress-tools-server-heartbeats
  namespace: observability
spec:
  description: "Policy for prometheus-egress-tools-server-heartbeats"
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: kube-prometheus-stack-prometheus
      app.kubernetes.io/name: prometheus
  egress:
    - toFQDNs:
        - matchName: tools.srv.${BASE_DOMAIN}
      toPorts:
        - ports:
            - port: "80" # heartbeats metrics
              protocol: TCP
            - port: "443" # heartbeats metrics
              protocol: TCP
