---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - containeroo.yaml
  - gitlab.yaml
  - grafana.yaml
  - jetstack.yaml
  - k8s-at-home.yaml
  - k8up-io.yaml
  - kubernetes-dashboard.yaml
  - metallb.yaml
  - metrics-server.yaml
  - minio.yaml
  - nfs-subdir-external-provisioner.yaml
  - prometheus-community.yaml
  - stakater.yaml
  - traefik.yaml
