---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - appuio.yaml
  - bitnami.yaml
  - containeroo.yaml
  - gitlab.yaml
  - goauthentik.yaml
  - grafana.yaml
  - hajimari.yaml
  - infracloudio.yaml
  - jetstack.yaml
  - kubernetes-dashboard.yaml
  - metallb.yaml
  - nfs-subdir-external-provisioner.yaml
  - prometheus-community.yaml
  - stakater.yaml
  - traefik.yaml
