---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: envoy-gateway-egress-prometheus-pushgateway
  namespace: network
spec:
  endpointSelector:
    matchLabels:
      gateway.envoyproxy.io/owning-gateway-name: envoy-internal
      gateway.envoyproxy.io/owning-gateway-namespace: network
  egress:
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: prometheus-pushgateway
            app.kubernetes.io/name: prometheus-pushgateway
            "k8s:io.kubernetes.pod.namespace": observability
      toPorts:
        - ports:
            - port: "9091"
              protocol: TCP
