---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: prometheus-blackbox-exporter-sso
  namespace: observability
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: prometheus-blackbox-exporter
  oidc:
    provider:
      issuer: https://sso.${BASE_DOMAIN}/realms/master
    clientID: envoy-gateway
    clientSecret:
      name: ${BASE_DOMAIN/./-}-sso-client-secret
