---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium.yaml
  - cloudnative-pg.yaml
  - containeroo.yaml
  - coredns.yaml
  - falcosecurity.yaml
  - gitlab.yaml
  - grafana.yaml
  - jetstack.yaml
  - k8up-io.yaml
  - metrics-server.yaml
  - minio.yaml
  - nfs-subdir-external-provisioner.yaml
  - prometheus-community.yaml
  - stakater.yaml
  - valkey.yaml
