---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - cilium.yaml
  - cloudflare-operator.yaml
  - cnpg-system.yaml
  - debug.yaml
  - falco.yaml
  - filebrowser.yaml
  - gitlab.yaml
  - healthchecks.yaml
  - k8up.yaml
  - keyclaok.yaml
  - media.yaml
  - minio.yaml
  - miracle.yaml
  - motus.yaml
  - network.yaml
  - nextcloud.yaml
  - observability.yaml
  - reloader.yaml
  - renovate.yaml
  - snapraid.yaml
  - storage-system.yaml
  - syncflaer.yaml
  - vimbin.yaml
  - wiki.yaml
