---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: prometheus-egress-flux-system
  namespace: observability
spec:
  description: "Policy for prometheus-egress-flux-system"
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: kube-prometheus-stack-prometheus
      app.kubernetes.io/name: prometheus
  egress:
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/component: helm-controller
            "k8s:io.kubernetes.pod.namespace": flux-system
        - matchLabels:
            app.kubernetes.io/component: notification-controller
            "k8s:io.kubernetes.pod.namespace": flux-system
        - matchLabels:
            app.kubernetes.io/component: source-controller
            "k8s:io.kubernetes.pod.namespace": flux-system
        - matchLabels:
            app.kubernetes.io/component: kustomize-controller
            "k8s:io.kubernetes.pod.namespace": flux-system
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
