---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: forward-auth
  namespace: traefik
spec:
  endpointSelector:
    matchLabels:
      app: forward-auth
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: traefik-traefik
            app.kubernetes.io/name: traefik
            io.kubernetes.pod.namespace: traefik
      toPorts:
        - ports:
            - port: "4181"
              protocol: TCP
