---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  component: keycloak
resources:
  - networkpolicies
  - ingress.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
  - statefulset.yaml
