---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-controller.yaml
  - kustomize-controller.yaml
  - notification-controller.yaml
  - source-controller.yaml
  - traefik-egress-flux-webhook-receiver.yaml
