---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: prometheus-egress-prometheus-smartctl-exporter
  namespace: observability
spec:
  description: "Policy for prometheus-egress-prometheus-smartctl-exporter"
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: kube-prometheus-stack-prometheus
      app.kubernetes.io/name: prometheus
  egress:
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: prometheus-smartctl-exporter
            app.kubernetes.io/instance: prometheus-smartctl-exporter
            "k8s:io.kubernetes.pod.namespace": observability
      toPorts:
        - ports:
            - port: "9633"
              protocol: TCP
