---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: prometheus-smartctl-exporter
  namespace: observability
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus-smartctl-exporter
      app.kubernetes.io/instance: prometheus-smartctl-exporter
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: kube-prometheus-stack-prometheus
            app.kubernetes.io/name: prometheus
            "k8s:io.kubernetes.pod.namespace": observability
      toPorts:
        - ports:
            - port: "9633"
              protocol: TCP
