---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager/
  - cloudflare-operator/
  - cloudnative-pg/
  - cnpg-plugin-barman-cloud/
  - k8up/
  - kube-prometheus-stack/
