---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - networkpolicies
  - envoyextensionpolicy.yaml
  - helmrelease.yaml
  - httproute.yaml
  - secret.yaml
  - tcproute.yaml
