---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - envoy-gateway-egress-falco.yaml
  - falco-k8s-metacollector.yaml
  - falco-sidekick-ui-redis.yaml
  - falco-sidekick-ui.yaml
  - falco-sidekick.yaml
  - falco.yaml
