---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: filebrowser
resources:
  - networkpolicies
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - persistentvolumeclaim.yaml
  - schedule.yaml
  - service.yaml
