apiVersion: v1
kind: Secret
metadata:
    name: kube-prometheus-stack-grafana-settings
    namespace: monitoring
type: Opaque
stringData:
    GRAFANA_AUTH_CLIENT_ID: ENC[AES256_GCM,data:cOpaG5MkyYp5VTMX3jnRfVtO,iv:ds10tZJRAV1csohmk4nF3u83xRVcbfzKfsbk6846RLM=,tag:LXJ/O119ewJ+O1BUvI0OCQ==,type:str]
    GRAFANA_AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:ZknxVwlnkEjkA9726Uy8uSzRhUqzlS/iVcAnmAYXNUI=,iv:Csl8rXJT+lRrqXfOECzDfKcxTI1YJQExVGimAPJt1KQ=,tag:Y/p34QNbt3gDTP9mCIO8tw==,type:str]
sops:
    lastmodified: "2026-01-01T11:54:05Z"
    mac: ENC[AES256_GCM,data:RCOPzWNJtbPQ7BD3/DZT9xuXU8xR055FG2ei8HnCP/IeCBLmONrPm0CF/cSNJxF7EfEIM690RDaIx22KQg0+AMVc7+Xq7kg1lSMBmQI5dlu7OALfVZ8NNoh/jblLevPhT9LwWxNToULiX9u6qhNMPgra3M7q1TIKO8MVXCX4hvE=,iv:Xj991VQMpBMxaq/e3HjtqxVmwiosw4BFB2DpCcxIjAE=,tag:T2zuAJ78WjQQnQfU+O3yiw==,type:str]
    pgp:
        - created_at: "2026-01-01T11:54:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAArdoO78LY/JOm1xu/uGTe6bZ08JS5Ki8iL/wHOcHP1fiT
            G9ROjv6VFy0boDnBNd03LU1MQFns4XEdnA8vTZffq+gtw9S9YU4RAUnE7a27ndYI
            aBCenK+WEequseZzxB7q5ZWH5EtzKKuhdxhFsHJpOqHS75pJFfKbUiiGu52ph7yL
            Uwr6O0Xjjucowsb99vyo+AJj8KBlvqon0k6jEtpTkvkHv5UwfTcPemcmyj+/HBnD
            +OHqETU39yiylae7A2dif/5n7LFr1uCsAumNoZbK3oGuBxp6nMnmsDUoMY3M/dbv
            BljeDTi1Wz7aUrIL4RpadPXUjXe8x6SwLpOC5X2f0doqP5R2bTy2rpUMUs2gPL9L
            WdFt6nPp9ZuHqdivjY6koKBjB6O68AMiyvihlzWmxy8g5qaCmTTFmR9v/ICyvGXD
            0DWMtkbg42e4RDLJStLXKJQxUTHPclCbxdGlvjlY3ZK7lhH7OMwPlW3JOMXxlr4g
            pG8LJ2tvlMPILws0CP89dcruhLHze44eMZrI4/l2IUvQRoOy2AZIY3ZgoRJtcyni
            WW/AIASxZsGmm0EwxoG5ANXecX7oKfvcXYBlGLPeh0Ya2PC6wstjf8CY8W3dzFaF
            HiUtjPI2TYbcSplba4HsuK8A6eDmwhwz8dUMNf4caX30VwjWAvSwXq8QD8Fy32nU
            aAEJAhDqqG4sD5JH/5fC4fcJRrLJiA9O0e0YrHMFgFhUe5VvWU02DuWtFP5uUppj
            nlYCYyoKKiPseyUbuh3a3WzD4jaByC54tbZY3mVTfh1Gts+81v8wgU2WDao2L6Ck
            Vv4r5J3gooc6
            =bae+
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: kube-prometheus-stack-helm-values
    namespace: monitoring
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:KWWXIsFOjCl0C9mt/08CqxsHJ41XW//a3HOdTDLnr6e9liexeefdbbMsgo/slY+UqLRM/e/FkbuCAqCmRJfLFNuZDeEOPSjCiNcrVrdEYDlSc8AAq5c6AgV4YvLvWvPAgiY0ZJywWn37EJW7QlOctFMxCvbrpIDAAerDkZZCeWSf3NU1DPCoJLuC4QM3VaFyfOzWW7ZWLys65NnZqtT8MYPAVFh6foUeWx2cXZoZIEsgirvQs26VfgWB92NNGCOVLav6zw==,iv:4ZA3qy5HWHPvGyuAuIFtUk15YX1E98rnllkZ/QwsWxM=,tag:j2K0OcunS1f0ZpYqk5TRdw==,type:str]
sops:
    lastmodified: "2026-01-01T11:54:05Z"
    mac: ENC[AES256_GCM,data:RCOPzWNJtbPQ7BD3/DZT9xuXU8xR055FG2ei8HnCP/IeCBLmONrPm0CF/cSNJxF7EfEIM690RDaIx22KQg0+AMVc7+Xq7kg1lSMBmQI5dlu7OALfVZ8NNoh/jblLevPhT9LwWxNToULiX9u6qhNMPgra3M7q1TIKO8MVXCX4hvE=,iv:Xj991VQMpBMxaq/e3HjtqxVmwiosw4BFB2DpCcxIjAE=,tag:T2zuAJ78WjQQnQfU+O3yiw==,type:str]
    pgp:
        - created_at: "2026-01-01T11:54:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAArdoO78LY/JOm1xu/uGTe6bZ08JS5Ki8iL/wHOcHP1fiT
            G9ROjv6VFy0boDnBNd03LU1MQFns4XEdnA8vTZffq+gtw9S9YU4RAUnE7a27ndYI
            aBCenK+WEequseZzxB7q5ZWH5EtzKKuhdxhFsHJpOqHS75pJFfKbUiiGu52ph7yL
            Uwr6O0Xjjucowsb99vyo+AJj8KBlvqon0k6jEtpTkvkHv5UwfTcPemcmyj+/HBnD
            +OHqETU39yiylae7A2dif/5n7LFr1uCsAumNoZbK3oGuBxp6nMnmsDUoMY3M/dbv
            BljeDTi1Wz7aUrIL4RpadPXUjXe8x6SwLpOC5X2f0doqP5R2bTy2rpUMUs2gPL9L
            WdFt6nPp9ZuHqdivjY6koKBjB6O68AMiyvihlzWmxy8g5qaCmTTFmR9v/ICyvGXD
            0DWMtkbg42e4RDLJStLXKJQxUTHPclCbxdGlvjlY3ZK7lhH7OMwPlW3JOMXxlr4g
            pG8LJ2tvlMPILws0CP89dcruhLHze44eMZrI4/l2IUvQRoOy2AZIY3ZgoRJtcyni
            WW/AIASxZsGmm0EwxoG5ANXecX7oKfvcXYBlGLPeh0Ya2PC6wstjf8CY8W3dzFaF
            HiUtjPI2TYbcSplba4HsuK8A6eDmwhwz8dUMNf4caX30VwjWAvSwXq8QD8Fy32nU
            aAEJAhDqqG4sD5JH/5fC4fcJRrLJiA9O0e0YrHMFgFhUe5VvWU02DuWtFP5uUppj
            nlYCYyoKKiPseyUbuh3a3WzD4jaByC54tbZY3mVTfh1Gts+81v8wgU2WDao2L6Ck
            Vv4r5J3gooc6
            =bae+
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-slack-webhook
    namespace: monitoring
type: Opaque
stringData:
    slack_api_url: ENC[AES256_GCM,data:3Qz7QHheMhRGHsVsNTRMR76bNRg818bvbbwHXOoLWy4Jq42cqdDoDN0fKPcgd44GWmIygkLOE6eD7AoMFm7Oy1u3eU2JvZKlJjCYB4utzA==,iv:IpWsdlzwiGRKHcMymr0AqVN3i0OdDq50tD/n0yFbXIA=,tag:8pVB60UdRqQk4oj1xAHssQ==,type:str]
sops:
    lastmodified: "2026-01-01T11:54:05Z"
    mac: ENC[AES256_GCM,data:RCOPzWNJtbPQ7BD3/DZT9xuXU8xR055FG2ei8HnCP/IeCBLmONrPm0CF/cSNJxF7EfEIM690RDaIx22KQg0+AMVc7+Xq7kg1lSMBmQI5dlu7OALfVZ8NNoh/jblLevPhT9LwWxNToULiX9u6qhNMPgra3M7q1TIKO8MVXCX4hvE=,iv:Xj991VQMpBMxaq/e3HjtqxVmwiosw4BFB2DpCcxIjAE=,tag:T2zuAJ78WjQQnQfU+O3yiw==,type:str]
    pgp:
        - created_at: "2026-01-01T11:54:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVARAArdoO78LY/JOm1xu/uGTe6bZ08JS5Ki8iL/wHOcHP1fiT
            G9ROjv6VFy0boDnBNd03LU1MQFns4XEdnA8vTZffq+gtw9S9YU4RAUnE7a27ndYI
            aBCenK+WEequseZzxB7q5ZWH5EtzKKuhdxhFsHJpOqHS75pJFfKbUiiGu52ph7yL
            Uwr6O0Xjjucowsb99vyo+AJj8KBlvqon0k6jEtpTkvkHv5UwfTcPemcmyj+/HBnD
            +OHqETU39yiylae7A2dif/5n7LFr1uCsAumNoZbK3oGuBxp6nMnmsDUoMY3M/dbv
            BljeDTi1Wz7aUrIL4RpadPXUjXe8x6SwLpOC5X2f0doqP5R2bTy2rpUMUs2gPL9L
            WdFt6nPp9ZuHqdivjY6koKBjB6O68AMiyvihlzWmxy8g5qaCmTTFmR9v/ICyvGXD
            0DWMtkbg42e4RDLJStLXKJQxUTHPclCbxdGlvjlY3ZK7lhH7OMwPlW3JOMXxlr4g
            pG8LJ2tvlMPILws0CP89dcruhLHze44eMZrI4/l2IUvQRoOy2AZIY3ZgoRJtcyni
            WW/AIASxZsGmm0EwxoG5ANXecX7oKfvcXYBlGLPeh0Ya2PC6wstjf8CY8W3dzFaF
            HiUtjPI2TYbcSplba4HsuK8A6eDmwhwz8dUMNf4caX30VwjWAvSwXq8QD8Fy32nU
            aAEJAhDqqG4sD5JH/5fC4fcJRrLJiA9O0e0YrHMFgFhUe5VvWU02DuWtFP5uUppj
            nlYCYyoKKiPseyUbuh3a3WzD4jaByC54tbZY3mVTfh1Gts+81v8wgU2WDao2L6Ck
            Vv4r5J3gooc6
            =bae+
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    version: 3.11.0
