apiVersion: v1
kind: Secret
metadata:
    name: kube-prometheus-stack-grafana-settings
    namespace: monitoring
type: Opaque
stringData:
    GRAFANA_AUTH_CLIENT_ID: ENC[AES256_GCM,data:U0dwF6dHZ/IqQ+0rFZF+Mft6,iv:197FZnfXl5O2SWptj50oztdjLgzbF4CK1qGU6KnO0us=,tag:LKKovwlMJDm/lVRjXpW79g==,type:str]
    GRAFANA_AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:08t95+IjwFJifLMbWXL3H9yr2kcNJqRgOQ4vr2qMjiA=,iv:fGFwSpTHDYqvZalgM3B1x5++pshME6T9nXBQaIn9taA=,tag:Txgadbkddj2mUOCajkwi3w==,type:str]
sops:
    lastmodified: "2026-01-01T12:43:23Z"
    mac: ENC[AES256_GCM,data:VVJFXZ/POkkfUutb9rCm1VVKkCwrth3l8aJP1++KkPz61Rg6RHst0sxz2FbnEXoxBtqqnl+DBnkn/NyHNRd7rpyCQ53Xk4syvUyZToqfFdKrO0ciLFntp6NblVEcjxAthWmPD4Jm/KEiYxwgJ1TFkn7XcGfJnALvebjMYSFV93E=,iv:a5A93XrLmcB5aaBbm/sK+WNb0zOxRqwjfAwA6MMXKpg=,tag:hejMWX+DiFZtPUiAsHnHoA==,type:str]
    pgp:
        - created_at: "2026-01-01T12:43:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ/9HcNSFI4SlJaJVkqyKdnLdUNIrYGSupvLqN7krQYFf3vh
            2gupZOQyxOwF3yxZIoXPHt9u+DNyAqURN3N9kZ0NyS7CA3Ag/g5s8u6SMDXBmqPH
            Nc073iTgojf2Za580OBYNwwX4l2d9s7Nh+dwwBINUmqk/QVaduEfDCWqSM7cAfvr
            qVe7fXnquOA+ahxbCwAFXSqWDeYwE8WELdpdGh5vm88/kQxJ0KagbAdzr6tgH1ux
            H/8KHuRO1Cv/efiXLoc8NNf5DeNZSK8z9JHgMneV5MN5AXNPD9PmiaBP/+i1WW34
            7QXsBEm+HLjJq/FStWTEBmXU93nrP4+SDCLUGA0lvfBZDHheEqeQE+OHqKuYHsi3
            pTITQ2hmvON9Em1KxTVBLLNrAPoYFcO9MoVs4A5WNykwB3kBBRSoP6CnMZPopZ9l
            BnauGpBBPYHoYwns/ko11mcZ9jYDTFI3IpmP3DLwfJ7GV6i+MnD2H7tlsVAhbt+T
            hHbq8qWoZvA0xdcoEtUWEjS9QtfkoRt3cI25MXBf3KKYYwow2cmMr8A3ZAjguk49
            eIiHBSlOdVI2jNEuBc2rP3cqpdoSHT1AyMkz+jQc+mLlyr6AJkRnKj/0pMnA8Y2a
            /4z76CJULYEuS2slmfh0jay1/zhCFAG0q1iZ9h7DPYl4vMY0GSoty7Vqr8wJQ9PU
            aAEJAhBjmlvPKnAbQFvTNVwMnLlt74IUaGE/asmNeWNFXdJ0u+zfda4PK53AhtXg
            zjld62oj+8tfMOLYSE702UiPBu+NPpF6pBdHUCtUUYDwbkD/RWxn6M/Tiozg2UsK
            3gMUeKtu7ouH
            =pd9y
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: kube-prometheus-stack-helm-values
    namespace: monitoring
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:xicl5ymwNtKwVsTyA+48ESHOo7pYoCkzxrMGAtqudoARsDoCPDvK3Ak7sqqGVt5tznMgHvl9SDUckP94oTIO53wuSLuAd/rQYtT0AssgXaMhwwYRhjvzqJ0jrzPzU9x071xF+pMOX6sM+xVX6kZbNPZ3sJuYDeJptIeedJ9cGZpB2FPCzOpu6lqFWp85utn9Odqtpoj7uCjBIfkOvHJ97wdiFL3D6msMk0ey4lwsS3pGUV1fScSvzLPC66WnbpdYUoX48Q==,iv:NmQgIbJ/SDblJC/eUuzLNZHzraCrZ69JosnkYIL/8Cc=,tag:pSemfEgfoxMRFzyI0nnzoA==,type:str]
sops:
    lastmodified: "2026-01-01T12:43:23Z"
    mac: ENC[AES256_GCM,data:VVJFXZ/POkkfUutb9rCm1VVKkCwrth3l8aJP1++KkPz61Rg6RHst0sxz2FbnEXoxBtqqnl+DBnkn/NyHNRd7rpyCQ53Xk4syvUyZToqfFdKrO0ciLFntp6NblVEcjxAthWmPD4Jm/KEiYxwgJ1TFkn7XcGfJnALvebjMYSFV93E=,iv:a5A93XrLmcB5aaBbm/sK+WNb0zOxRqwjfAwA6MMXKpg=,tag:hejMWX+DiFZtPUiAsHnHoA==,type:str]
    pgp:
        - created_at: "2026-01-01T12:43:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxCiAiPlgInVAQ/9HcNSFI4SlJaJVkqyKdnLdUNIrYGSupvLqN7krQYFf3vh
            2gupZOQyxOwF3yxZIoXPHt9u+DNyAqURN3N9kZ0NyS7CA3Ag/g5s8u6SMDXBmqPH
            Nc073iTgojf2Za580OBYNwwX4l2d9s7Nh+dwwBINUmqk/QVaduEfDCWqSM7cAfvr
            qVe7fXnquOA+ahxbCwAFXSqWDeYwE8WELdpdGh5vm88/kQxJ0KagbAdzr6tgH1ux
            H/8KHuRO1Cv/efiXLoc8NNf5DeNZSK8z9JHgMneV5MN5AXNPD9PmiaBP/+i1WW34
            7QXsBEm+HLjJq/FStWTEBmXU93nrP4+SDCLUGA0lvfBZDHheEqeQE+OHqKuYHsi3
            pTITQ2hmvON9Em1KxTVBLLNrAPoYFcO9MoVs4A5WNykwB3kBBRSoP6CnMZPopZ9l
            BnauGpBBPYHoYwns/ko11mcZ9jYDTFI3IpmP3DLwfJ7GV6i+MnD2H7tlsVAhbt+T
            hHbq8qWoZvA0xdcoEtUWEjS9QtfkoRt3cI25MXBf3KKYYwow2cmMr8A3ZAjguk49
            eIiHBSlOdVI2jNEuBc2rP3cqpdoSHT1AyMkz+jQc+mLlyr6AJkRnKj/0pMnA8Y2a
            /4z76CJULYEuS2slmfh0jay1/zhCFAG0q1iZ9h7DPYl4vMY0GSoty7Vqr8wJQ9PU
            aAEJAhBjmlvPKnAbQFvTNVwMnLlt74IUaGE/asmNeWNFXdJ0u+zfda4PK53AhtXg
            zjld62oj+8tfMOLYSE702UiPBu+NPpF6pBdHUCtUUYDwbkD/RWxn6M/Tiozg2UsK
            3gMUeKtu7ouH
            =pd9y
            -----END PGP MESSAGE-----
          fp: 3AE9F6BBA8327432196EF588637ED0A1DCC83334
    encrypted_regex: ^(data|stringData|customRequestHeaders)$
    version: 3.11.0
