---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alertmanager-egress-heartbeats.yaml
  - alertmanager.yaml
  - egress-kube-prometheus-stack-admission-create-job.yaml
  - egress-kube-prometheus-stack-admission-patch-job.yaml
  - envoy-gateway-egress-alertmanager.yaml
  - envoy-gateway-egress-grafana.yaml
  - envoy-gateway-egress-prometheus.yaml
  - grafana.yaml
  - kube-prometheus-stack-operator.yaml
  - kube-state-metrics.yaml
  - prometheus.yaml
