---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: alertmanager-egress-healthchecks
  namespace: monitoring
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: alertmanager
      app.kubernetes.io/instance: kube-prometheus-stack-alertmanager
  egress:
    - toServices:
        - k8sService:
            serviceName: healthchecks
            namespace: healthchecks
      toPorts:
        - ports:
            - port: "8000"
              protocol: TCP
