---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-postgres
  namespace: wiki
  labels:
    app: wiki
    component: postgres
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki
      component: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        k8up.io/backupcommand: pg_dumpall -U wikijs -h 127.0.0.1
        k8up.io/file-extension: .sql
      labels:
        app: wiki
        component: postgres
    spec:
      containers:
        - name: wiki-postgres
          image: postgres:14.1-alpine
          envFrom:
            - secretRef:
                name: wiki-postgres
          env:
            - name: TZ
              value: Europe/Zurich
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          startupProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U "$POSTGRES_USER" --dbname=wikijs -h 127.0.0.1 -p 5432
            initialDelaySeconds: 5
            failureThreshold: 30
            periodSeconds: 2
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U "$POSTGRES_USER" --dbname=wikijs -h 127.0.0.1 -p 5432
            failureThreshold: 2
            timeoutSeconds: 3
            periodSeconds: 30
      restartPolicy: Always
      automountServiceAccountToken: false
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: wiki-postgres-data
