---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudnative-pg-egress-keycloak-postgres.yaml
  - minio-ingress-keycloak-postgres.yaml
  - postgres.yaml
  - prometheus-egress-keycloak-postgres.yaml
