---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - capacitor-next
  - cascader
  - cert-manager
  - cilium
  - cloudflare-operator
  - cloudnative-pg
  - debug
  - falco
  - filebrowser
  - gitlab
  - healthchecks
  - k8up
  - keycloak
  - kube-system
  - media
  - minio
  - monitoring
  - network
  - nextcloud
  - reloader
  - renovate
  - snapraid
  - storage
  - vimbin
  - wiki
