---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - capacitor-next/
  - debug/
  - falco/
  - filebrowser/
  - gitlab/
  - healthchecks/
  - keycloak/
  - media/
  - minio/
  - motus/
  - nextcloud/
  - renovate/
  - snapraid/
  - vimbin/
  - wiki/
