---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager/
  - cilium/
  - cloudflare-operator/
  - cnpg-system/
  - k8up/
  - kube-system/
  - network/
  - observability/
  - reloader/
  - storage/
