---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - networkpolicies
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - cronjob.yaml
  - prometheusrule.yaml
  - secret.yaml
  - serviceaccount.yaml
