---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - networkpolicies
  - clienttrafficpolicy.yaml
  - envoypatchpolicy.yaml
  - envoyproxy.yaml
  - gateway-external.yaml
  - gateway-internal.yaml
  - gatewayclass.yaml
  - helmrelease.yaml
  - redirect.yaml
