---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: prometheus-egress-vpn-server-node-exporter
  namespace: observability
spec:
  description: "Policy for prometheus-egress-vpn-server-node-exporter"
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: kube-prometheus-stack-prometheus
      app.kubernetes.io/name: prometheus
  egress:
    - toFQDNs:
        - matchName: vpn.srv.${BASE_DOMAIN}
      toPorts:
        - ports:
            - port: "9100" # prometheus node exporter
              protocol: TCP
