---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - plex
  - prowlarr
  - radarr
  - sabnzbd
  - sonarr
  - tautulli
  - envoypatchpolicy.yaml
  - schedule.yaml
  - secret.yaml
  - securitypolicy.yaml
