---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  dependsOn:
    - name: metallb
      namespace: metallb
    - name: cert-manager
      namespace: cert-manager
  chart:
    spec:
      chart: traefik
      version: 10.14.2
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 5m
  values:
    additionalArguments:
      - --api.insecure=true
      - --entrypoints.websecure.http.middlewares=traefik-default-headers@kubernetescrd
      - --serverstransport.insecureskipverify
      - --providers.kubernetesingress.ingressendpoint.ip=${METALLB_TRAEFIK_ADDRESS_POOL%/*}
    globalArguments: null
    env:
      - name: TZ
        value: Europe/Zurich
    ingressClass:
      enabled: true
      fallbackApiVersion: v1
      isDefaultClass: true
    ingressRoute:
      dashboard:
        enabled: false
    logs:
      general:
        level: INFO
    pilot:
      dashboard: false
      enabled: false
    ports:
      gitlab-ssh:
        expose: true
        exposedPort: 22
        port: 2222
        protocol: TCP
      traefik:
        expose: true
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
    service:
      annotations:
        metallb.universe.tf/address-pool: traefik
      spec:
        externalTrafficPolicy: Local
    experimental:
      plugins:
        enabled: true
  valuesFrom:
    - kind: Secret
      name: traefik-helm-values
      optional: false
  install:
    crds: Skip
  upgrade:
    crds: Skip
