---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  HOST_IP_V4: 10.0.0.9
  DNS_IP: 10.0.0.2
  INGRESS_NGINX_LB_IP: 10.0.1.200
  CILIUM_LB_DEFAULT_RANGE_START_V4: 10.0.1.201
  CILIUM_LB_DEFAULT_RANGE_END_V4: 10.0.1.210
  LAN_NETWORK_RANGE_V4: 10.0.0.0/23
  POD_NETWORK_RANGE_V4: 10.1.0.0/16
