---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - envoy-gateway-egress-prometheus-pushgateway.yaml
  - prometheus-egress-prometheus-pushgateway.yaml
  - prometheus-pushgateway.yaml
  - securitypolicy.yaml
