---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - networkpolicies/
  - cnpg-cluster.yaml
  - cnpg-registry-database.yaml
  - objectstore.yaml
  - scheduledbackup.yaml
  - secret.yaml
