---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: traefik-egress-sonarr
  namespace: traefik
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: traefik-traefik
  egress:
    - toServices:
        - k8sService:
            serviceName: sonarr
            namespace: media
      toPorts:
        - ports:
            - port: "8989"
              protocol: TCP
